In [1]:
import tensorflow as tf
print(tf.__version__)

2.4.1


### Create tensors

In [2]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
scalar.ndim

0

In [4]:
vector = tf.constant([10, 7])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>

In [5]:
vector.ndim

1

In [7]:
matrix = tf.constant([[10, 7],
                     [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [8]:
matrix.ndim

2

In [9]:
matrix2 = tf.constant([[10, 7],
                       [7, 10],
                       [1, 3]])
matrix2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10],
       [ 1,  3]])>

In [10]:
matrix2.ndim

2

In [11]:
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                     
                      [[7, 8, 9],
                       [10, 11, 12]],
                      
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [12]:
tensor.ndim

3

* **scalar:** a single value
* **vector:** a number with direction
* **matrix:** a 2-dimensional array of numbers
* **tensor:** a n-dimensional array of numbers

In [13]:
mutable_tensor = tf.Variable([10, 7])
immutable_tensor = tf.constant([10, 7])
mutable_tensor, immutable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [14]:
mutable_tensor[0] = 3
mutable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [15]:
mutable_tensor[0].assign(3)
mutable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 7])>

In [16]:
immutable_tensor[0].assign(3)
immutable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

### Create Random Tensors

In [17]:
random1 = tf.random.Generator.from_seed(42)
rand_tensor1 = random1.normal(shape=(3, 2))
rand_tensor1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [18]:
rand_tensor1.ndim

2

In [28]:
random2 = tf.random.Generator.from_seed(42)
rand_tensor2 = random2.normal(shape=(3, 2))
rand_tensor2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [23]:
rand_tensor1 == rand_tensor2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [False, False],
       [False, False]])>

In [30]:
not_shuffled = tf.constant([[1, 2, 3],
                            [4, 5, 6],
                            [7, 8, 9]])
not_shuffled, not_shuffled.ndim

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])>,
 2)

In [40]:
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])>

### Creating tensors with only ones or zeros

In [41]:
ones = tf.ones(shape=(3, 2))
ones

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [42]:
zeros = tf.zeros(shape=(2, 3))
zeros

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

### Creating a tensor from a numpy array

In [50]:
import numpy as np

numpy_arr = np.arange(1, 25, dtype=np.int32)
numpy_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [54]:
numpy_tensor = tf.constant(numpy_arr, shape=(2, 3, 4))
numpy_tensor

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

In [55]:
2 * 3 * 4

24

### Get information about a tensor

* **Shape**
* **Rank**
* **Axis**
* **Size**

In [56]:
rank_4_tensor = tf.zeros([2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [57]:
print('Datatype of every element:', rank_4_tensor.dtype)
print('Number of dimensions (rank):', rank_4_tensor.ndim)
print('Shape of tensor:', rank_4_tensor.shape)
print('Elements along axis 0 of tensor:', rank_4_tensor.shape[0])
print('Elements along last axis of tensor', rank_4_tensor.shape[-1])
print('Total number of elements (size). (2*3*4*5)', tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor 5
Total number of elements (size). (2*3*4*5) 120


In [60]:
# Get the first 2 items in each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [61]:
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4]])
rank_2_tensor, rank_2_tensor.ndim

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]])>,
 2)

In [62]:
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4])>

In [63]:
# Add extra dimension to a tensor at the end
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]])>

In [64]:
rank_3_tensor.ndim

3

In [67]:
# Add dimension with tf.expand_dims()
rank_3_tensor = tf.expand_dims(rank_2_tensor, axis=-1)
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]])>

### Manipulating tensors 

In [68]:
tensor = tf.constant([[1, 2],
                      [3, 4]])

In [69]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [71]:
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[101, 102],
       [103, 104]])>

In [72]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-9, -8],
       [-7, -6]])>

In [73]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]])>

In [74]:
tensor / 10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.1, 0.2],
       [0.3, 0.4]])>

In [75]:
tf.add(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]])>

In [76]:
tf.multiply(tensor, 12)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12, 24],
       [36, 48]])>

### Matrix Multiplication

In [77]:
tensor1 = tf.constant([[7, 10],
                       [3, 5]])

tf.matmul(tensor1, tensor1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 79, 120],
       [ 36,  55]])>

In [80]:
tensor1 @ tensor1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 79, 120],
       [ 36,  55]])>

In [90]:
tensor2 = tf.constant([[1, 2],
                       [3, 4],
                       [5, 6]])

tensor3 = tf.constant([[7, 8],
                       [9, 10],
                       [11, 12]])

tensor2, tensor3

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>)

In [81]:
tensor2 @ tensor3

InvalidArgumentError: Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul]

shape(3, 2) * shape(3, 2) Does not work
shape(2, 3) * shape(3, 2) Works
shape(3, 2) * shape(2, 3) Works

In [91]:
tensor3

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]])>

In [92]:
tf.reshape(tensor3, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]])>

In [93]:
tensor2 @ tf.reshape(tensor3, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [94]:
tf.transpose(tensor3)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  9, 11],
       [ 8, 10, 12]])>

In [95]:
tensor2 @ tf.transpose(tensor3)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]])>

In [97]:
tf.matmul(tensor2, tensor3, transpose_a=True, transpose_b=False)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [98]:
tf.tensordot(tf.transpose(tensor2), tensor3, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

### Converting tensor datatype

In [101]:
tensor_a = tf.constant([1.7, 3.5])
tensor_a

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 3.5], dtype=float32)>

In [106]:
tensor_b = tf.constant([1, 4])
tensor_b

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 4])>

In [105]:
tensor_a = tf.cast(tensor_a, dtype=tf.float16)
tensor_a

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 3.5], dtype=float16)>

In [107]:
tensor_b = tf.cast(tensor_b, dtype=tf.float32)
tensor_b

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 4.], dtype=float32)>

In [108]:
tensor_c = tf.cast(tensor_a, dtype=tf.int32)
tensor_c

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 3])>

### Get tensor absolute values

In [109]:
tensor = tf.constant([-7, -22, 4])
tf.abs(tensor)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 7, 22,  4])>

### Tensor Aggregation

In [110]:
tensor = tf.constant(np.random.randint(low=0, high=100, size=50))
tensor

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([94, 89, 82, 11, 10,  0, 69, 18, 12, 12, 19, 87,  8, 22, 49, 56, 24,
       23, 28, 61, 37, 38, 11, 33, 15, 62, 92, 17, 82, 52, 30, 59, 78, 55,
       14, 14, 89, 46,  7,  5, 61, 76, 10, 54, 89, 62, 50, 62, 53, 25])>

In [111]:
tf.reduce_min(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [112]:
tf.reduce_max(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=94>

In [113]:
tf.reduce_mean(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=43>

In [114]:
tf.reduce_sum(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2152>

### Squeezing tensors

In [115]:
tensor = tf.constant(np.random.randint(0, 100, 50), shape=(1, 1, 1, 50))
tensor

<tf.Tensor: shape=(1, 1, 1, 50), dtype=int32, numpy=
array([[[[99,  4, 22, 14, 43, 66, 10, 78,  5, 93, 41, 69, 48, 69, 36,
          15, 79, 21, 79, 21, 35, 73, 94, 77,  2, 78, 22, 37, 37, 10,
          15,  2, 99, 66, 30, 12, 76, 87, 50, 39, 23, 71,  2, 37, 93,
          34, 25, 89, 80, 61]]]])>

In [116]:
tensor[0][0][0][14]

<tf.Tensor: shape=(), dtype=int32, numpy=36>

In [117]:
tensor = tf.squeeze(tensor)
tensor

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([99,  4, 22, 14, 43, 66, 10, 78,  5, 93, 41, 69, 48, 69, 36, 15, 79,
       21, 79, 21, 35, 73, 94, 77,  2, 78, 22, 37, 37, 10, 15,  2, 99, 66,
       30, 12, 76, 87, 50, 39, 23, 71,  2, 37, 93, 34, 25, 89, 80, 61])>

### One-hot encoding

In [120]:
some_values = [0, 1, 2, 3]
tf.one_hot(some_values, depth=4, on_value="yes", off_value="no")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yes', b'no', b'no', b'no'],
       [b'no', b'yes', b'no', b'no'],
       [b'no', b'no', b'yes', b'no'],
       [b'no', b'no', b'no', b'yes']], dtype=object)>